name: 🚀 Deploy Website

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ vars.FTP_USERNAME }}
        password: ${{ vars.FTP_PASSWORD }}
        port: 21
        protocol: ftp
        timeout: 60000 # Increase timeout to 60 seconds
        server-dir: /public_html/ # 000webhost uses /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          sql/**
          README.md
